### ISSUE TITLE
Upgrading Stock(Making History) Engine Plates Results in Negative Mass

### ISSUE THREAD

**Issue by Steampunk-Wizard** [linuxgurugamer/KRnD#5]
When you select an Engine plate (EP-18, EP-25, etc((At least those two show this bug))), the reported mass is significantly higher than the part's actual mass. This is probably a result of the change in KSP version 1.5 where all engine plates were given different masses for each size. The result of this however, is the part receiving negative mass after an upgrade or two, causing it to stick in place in the air and break any rocket launched with one. 

Confirming this, here is part of the KSP wiki reporting the engine plates as .075t across the board.
https://wiki.kerbalspaceprogram.com/wiki/Making_History_parts#Coupling
And here is the actual part page, reporting the far smaller and new mass of the part, ranging from 0.013t to 0.002t.
https://wiki.kerbalspaceprogram.com/wiki/EP-18_Engine_Plate

Looking at a modded part, the EP-12 Engine plate(From the MissingHistory Mod), it works completely fine, and KRnD correctly uses the lightest mass of the part to calculate upgrades, preventing it from ever going negative.

**Comment by linuxgurugamer** [comment]
KRnD get the info from the part itself at runtime.  The problem is that it doesn't know about part variants, and those part variants change the mass of the parts.  Sometime the amount it changes the mass is much more than the adjusted part mass, resulting in negative numbers.

The solution is not simple, I will have to now read in all the variants (or maybe just the current variant) and include those masses (or negative masses in those cases where the variant is reducing the mass)  in the final calculation

**Comment by linuxgurugamer** [comment]
Fixed
